"""initial migration

Revision ID: 400f5e41446d
Revises: 
Create Date: 2026-09-22 23:17:26.559239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '400f5e41446d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('fire_os_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('session_plans',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('energy_trajectory', sa.Text(), nullable=True),
    sa.Column('time_budget_minutes', sa.Integer(), nullable=True),
    sa.Column('total_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('plan_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_plans_device_id'), 'session_plans', ['device_id'], unique=False)
    op.create_table('taste_profiles',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('genre_weights', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('pacing_preference', sa.String(length=20), nullable=False),
    sa.Column('disliked_genres', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('avg_session_length_minutes', sa.Integer(), nullable=True),
    sa.Column('preferred_providers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_profiles_device_id'), 'taste_profiles', ['device_id'], unique=False)
    op.create_table('watch_history',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('episodes_watched', sa.Integer(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_history_device_id'), 'watch_history', ['device_id'], unique=False)
    op.create_table('mood_history',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('session_plan_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_history_device_id'), 'mood_history', ['device_id'], unique=False)
    op.create_table('session_feedback',
    sa.Column('session_plan_id', sa.String(length=36), nullable=False),
    sa.Column('overall_rating', sa.String(length=20), nullable=False),
    sa.Column('pacing_rating', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_plan_id')
    )
    op.create_table('session_picks',
    sa.Column('session_plan_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=False),
    sa.Column('genre_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('streaming_provider', sa.String(length=100), nullable=True),
    sa.Column('deep_link_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_plan_id'], ['session_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_picks_session_plan_id'), 'session_picks', ['session_plan_id'], unique=False)
    op.create_table('pick_feedback',
    sa.Column('session_pick_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_pick_id'], ['session_picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_pick_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_feedback')
    op.drop_index(op.f('ix_session_picks_session_plan_id'), table_name='session_picks')
    op.drop_table('session_picks')
    op.drop_table('session_feedback')
    op.drop_index(op.f('ix_mood_history_device_id'), table_name='mood_history')
    op.drop_table('mood_history')
    op.drop_index(op.f('ix_watch_history_device_id'), table_name='watch_history')
    op.drop_table('watch_history')
    op.drop_index(op.f('ix_taste_profiles_device_id'), table_name='taste_profiles')
    op.drop_table('taste_profiles')
    op.drop_index(op.f('ix_session_plans_device_id'), table_name='session_plans')
    op.drop_table('session_plans')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
